# Generated by Django 2.2.4 on 2019-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto')),
                ('estoque', models.IntegerField(verbose_name='Estoque')),
                ('valor', models.IntegerField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='cadastro_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('telefone', models.IntegerField(default=0, verbose_name='Telefone')),
                ('datanascimento', models.IntegerField(default=0, verbose_name='Data de Nascimento')),
                ('cpf', models.IntegerField(default=0, verbose_name='CPF')),
                ('cep', models.IntegerField(null=True, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, null=True, verbose_name='Bairro')),
                ('complemento', models.CharField(max_length=100, null=True, verbose_name='Complemento')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('senha', models.IntegerField(default=0, verbose_name='Senha')),
                ('confirmarsenha', models.IntegerField(default=0, verbose_name='Confirmar Senha')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
        ),
    ]
