# Generated by Django 2.2.4 on 2019-12-04 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('datanascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('cep', models.IntegerField(null=True, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, null=True, verbose_name='Bairro')),
                ('complemento', models.CharField(max_length=100, null=True, verbose_name='Complemento')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='cadastro_produtos',
            new_name='Produtos',
        ),
        migrations.DeleteModel(
            name='cadastro_usuario',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
